### ISSUE TITLE
PSNR

### ISSUE THREAD

**Issue by zouchen92** [JasonLSC/SteerNeRF_official#2]
Hello, I used your code to run all the datasets in the paper.

But I didn't get the results in the paper, and I don't know where I went wrong.

In the pretrain stage, I set frame=1 and in the joint train stage, frame=3, but the final result in TandT is 1dB lower than the psnr in the paper, and the final result in Synthetic is 3dB lower than the psnr in the paper.

How can I achieve the effect in your paper.

**Comment by JasonLSC** [comment]
Hi, thank you for your attention. I am willing to help you reproduce the results. 

The critical problems leading to the mismatch might be 1) the distillation process (mentioned in Sec.3.5 of the paper) and 2) the generation of the poses of preceding frames. The code related to these parts has yet to be open-sourced, so you might not faithfully reproduce our results.

Could you provide more details about how you do with distillation and the generation of the poses of preceding frames?

**Comment by zouchen92** [comment]
I tried running the synthetic dataset on 3090, as well as the synthetic dataset and TandT dataset on v100.

In addition to running the code using raw data downloaded from ngp pl, I also attempted to sort or interpolate based on the pose  order of the dataset.

The frame insertion utilizes the created_interp_traj. py file you provided.
![image](https://github.com/user-attachments/assets/fce3f2cf-3251-4a2c-b6e6-9aa1fb664542)

I made adjustments to the data reading in the code of nsvf. py based on whether frame interpolation was performed.
![image](https://github.com/user-attachments/assets/6928a22c-561e-4eda-b174-31cd8056be95)

**Comment by JasonLSC** [comment]
Ah, the file 'created_interp_traj.py' generates the poses for rendering at test time rather than poses of preceding frames for training radiance fields. 

The distillation of my implementation is to sample some poses near the training view and use a pre-trained radiance field to render images of these sampled poses as pseudo-ground truth for the joint training phase.

The method for generating preceding frames involves sampling a set of small displacements from a normal distribution to serve as the minor displacement between the current and previous frames. Then, based on this displacement, more preceding frames are linearly extrapolated.

**Comment by zouchen92** [comment]
Could I get your code for this part?

Or add your WX for further consultation.

**Comment by JasonLSC** [comment]
Thank you for your interest in our work. You are welcome to contact me further at jasonlisicheng@zju.edu.cn.
